# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.
FROM alpine
WORKDIR /app
COPY . .
CMD ["/app/redir", "-s"]