# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

version: "3"
services:
  redir:
    restart: always
    image: redir:latest
    environment:
      REDIR_CONF: ./data/redirconf.yml
    depends_on:
      - mongo
    deploy:
      replicas: 1
    networks:
      - traefik_proxy
  mongo:
    restart: always
    container_name: redirdb
    image: mongo:latest
    mem_limit: 512m
    memswap_limit: 1g
    ports:
      - "27018:27017"
    volumes:
      - ../data/mongo:/data/db
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
